CREATE TABLE BOOK_SALES (
    BOOK_ID NUMBER PRIMARY KEY,
    BOOK_TITLE VARCHAR2(100),
    UNIT_PRICE NUMBER(6,2),
    QUANTITY_SOLD NUMBER
);


INSERT INTO BOOK_SALES VALUES (1, 'The Silent Library', 35.50, 12);
INSERT INTO BOOK_SALES VALUES (2, 'Hidden Algorithms', 42.00, 7);
INSERT INTO BOOK_SALES VALUES (3, 'Chronicles of Data', 29.99, 26);
INSERT INTO BOOK_SALES VALUES (4, 'Oracle Odyssey', 55.00, 3);
INSERT INTO BOOK_SALES VALUES (5, 'The Lost Index', 24.75, 31);

COMMIT;